site_name: Marktstammdatenregister (MaStR) Datenmodell
site_description: Dokumentation des Marktstammdatenregister Datenmodells
docs_dir: docs
repo_name: mastr-docs
repo_url: https://github.com/OpenEnergyPlatform/mastr-docs


theme:
  name: material
  font: false
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.copy
    - toc.integrate

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - toc:
      toc_depth: 2-3
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
